#!/usr/bin/env node
// One-command local dev: boots a local Supabase stack, wires its credentials into
// .env.development.local (dev-only, so prod .env.local is left untouched), seeds a
// dev admin + sample post, then starts the Vite dev server.
//
//   npm run dev:local      start everything
//   npm run stop:local     tear down the Supabase stack
import { execSync, spawnSync, spawn } from 'node:child_process'
import { writeFileSync } from 'node:fs'

const DEV_EMAIL = process.env.DEV_ADMIN_EMAIL || 'admin@example.com'
const DEV_PASSWORD = process.env.DEV_ADMIN_PASSWORD || 'password123'

function run(cmd, opts = {}) {
  return execSync(cmd, { stdio: 'inherit', ...opts })
}

// 0. Preflight — the Supabase CLI must be installed (it drives Docker).
if (spawnSync('supabase', ['--version'], { stdio: 'ignore' }).status !== 0) {
  console.error(
    '✗ Supabase CLI not found. Install it first:\n' +
      '    brew install supabase/tap/supabase\n' +
      '  (and make sure Docker is running).',
  )
  process.exit(1)
}

// 1. Boot the local stack (idempotent — no-op if already running).
console.log('▶ Starting local Supabase (Docker)…')
try {
  run('supabase start')
} catch {
  console.error('\n✗ `supabase start` failed — is Docker running?')
  process.exit(1)
}

// 2. Read the local credentials.
const status = JSON.parse(execSync('supabase status -o json').toString())
const url = status.API_URL
const anon = status.ANON_KEY
const serviceRole = status.SERVICE_ROLE_KEY

// 3. Point dev at the local stack (dev-only env file; prod .env.local untouched).
writeFileSync(
  '.env.development.local',
  `# Auto-generated by scripts/dev-local.mjs — points dev at local Supabase.\n` +
    `VITE_SUPABASE_URL=${url}\n` +
    `VITE_SUPABASE_ANON_KEY=${anon}\n`,
)
console.log(`▶ Wrote .env.development.local → ${url}`)

// 4. Seed a dev admin + sample post (idempotent).
run('node scripts/seed-e2e-user.mjs', {
  env: {
    ...process.env,
    SUPABASE_URL: url,
    SUPABASE_SERVICE_ROLE: serviceRole,
    E2E_ADMIN_EMAIL: DEV_EMAIL,
    E2E_ADMIN_PASSWORD: DEV_PASSWORD,
  },
})
console.log(`▶ Dev admin login: ${DEV_EMAIL} / ${DEV_PASSWORD}`)
console.log(
  '  Supabase Studio: http://127.0.0.1:54323  ·  stop with: yarn stop:local\n',
)

// 5. Start Vite (inherits stdio; Ctrl-C stops dev, Supabase keeps running).
spawn('yarn', ['dev'], {
  stdio: 'inherit',
  shell: process.platform === 'win32',
})
